// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "13ad0ece-71c6-48d1-8988-535f441650aa";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onThingColorChange();
void onThingColoredLightChange();
void onThingBrightnessChange();
void onThingKelvinChange();

CloudColor thingColor;
CloudColoredLight thingColoredLight;
CloudDimmedLight thingBrightness;
int thingKelvin;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(thingColor, READWRITE, ON_CHANGE, onThingColorChange);
  ArduinoCloud.addProperty(thingColoredLight, READWRITE, ON_CHANGE, onThingColoredLightChange);
  ArduinoCloud.addProperty(thingBrightness, READWRITE, ON_CHANGE, onThingBrightnessChange);
  ArduinoCloud.addProperty(thingKelvin, READWRITE, ON_CHANGE, onThingKelvinChange, 1000);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
